resource_group_name = "slack-toolbox"
resource_group_location = "East US"
custom_topic_name = "selected-users-messages"
storage_account_name = "slacktoolboxmessages"
storage_account_queue_name = "selectedusermessages"
eventgrid_event_subscription_name = "unfiltered-messages"