name: Create User in AAD

on:
  push:
    branches:
      - main
    #paths:
    #  - 'terraform/azure/tier0/guest_users'

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN}}
  GITHUB_OWNER: ${{ secrets.GH_OWNER }}
  EXAMPLE_USER_AAD_USER_OBJECT_ID: ${{ secrets.EXAMPLE_USER_AAD_USER_OBJECT_ID }}
  NEW_USER_AAD_USER_PRINCIPAL_NAME: ${{ secrets.NEW_USER_AAD_USER_PRINCIPAL_NAME }}
  NEW_USER_AAD_USER_NAME: ${{ secrets.NEW_USER_AAD_USER_NAME }}
  NEW_USER_AAD_PASSWORD: ${{ secrets.NEW_USER_AAD_PASSWORD }}

jobs:

  Terraform_Plan:
    environment: ad-hoc
    name: Create User in AAD - Plan
    runs-on: ubuntu-latest
    strategy:
      matrix: { folder: [ 'terraform/azure/tier0/guest_users' ] }
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.folder }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print CWD
      run: pwd

    - name: Configure Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15.0

    - name: Get Terraform state
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -input=false -var 'user_principal_name=${{ env.NEW_USER_AAD_USER_PRINCIPAL_NAME }}' -var 'display_name=${{ env.NEW_USER_AAD_USER_NAME }}' -var 'mail_nickname=${{ env.NEW_USER_AAD_USER_NAME}}' -var 'password=${{ env.NEW_USER_AAD_PASSWORD}}'

  Terraform_Apply:
    needs: Terraform_Plan
    environment: ad-hoc
    name: Create User in AAD - Apply
    runs-on: ubuntu-latest
    strategy:
      matrix: { folder: [ 'terraform/azure/tier0/guest_users' ] }
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.folder }}
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Configure Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 0.15.0

        - name: Get Terraform state
          run: terraform init

        - name: Terraform Apply
          run: terraform apply -auto-approve -input=false -var 'user_principal_name=${{ env.NEW_USER_AAD_USER_PRINCIPAL_NAME }}' -var 'display_name=${{ env.NEW_USER_AAD_USER_NAME }}' -var 'mail_nickname=${{ env.NEW_USER_AAD_USER_NAME}}' -var 'password=${{ env.NEW_USER_AAD_PASSWORD}}'

        - name: Print AAD users
          run: terraform output all_users