name: Create Tier 0 Common Services Resources

on:
  pull_request

env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }} 
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN}}
  GITHUB_OWNER: ${{ secrets.GH_OWNER }}

jobs:

  read_users:
    environment: ad-hoc
    name: Create Tier 0 Common Services Resources - Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.folder }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print CWD
      run: pwd

    - name: Configure Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.15.0

    - name: Get Terraform state
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -input=false -var-file=config.tfvars

    - name: Print Terraform Outputs
      run: |
        echo "Tier 0 Resource Group ID: $(terraform output resource_group_id)"
        echo "Resource Group Name: $(terraform output resource_group_name)""